### ISSUE TITLE
Demo URL not working

### ISSUE THREAD

**Issue by tzake** [ltwlf/azure-functions-docker-html2pdf#1]
Example GET Request with URL parameter:

https://ltwlf-functions-html-to-pdf.azurewebsites.net/api/Html2Pdf?url=https://blog.leitwolf.io

Is it because you switched from anonymous to function auth?

**Comment by ltwlf** [comment]
Yes, this is because I switched from Anonymous to Function Auth,

**Comment by tzake** [comment]
Gotta hang on to those Azure credits, yes? 

Thanks for this repo.
